"""Architect Agent: Designs the system architecture, database schema, and API contracts."""
from framework.config import invoke_llm
from framework.tools.file_tool import write_file, read_file

SYSTEM_PROMPT = """You are a System Architect Agent specialized in designing secure web applications.
You design clean, maintainable architectures using modern patterns.
You must produce:
- Database schemas (Prisma)
- REST API contracts (OpenAPI-style documentation)
- Component trees
- Security models
- Decision logs with justifications"""

class ArchitectAgent:
    def __init__(self):
        self.name = "ArchitectAgent"
    
    def run(self, state):
        print(f"[{self.name}] Starting architecture design...")
        
        # Read research outputs
        research = state.get("research_report", "")
        mockups = state.get("mockups", "")
        
        user_prompt = f"""Design the complete system architecture for a whistleblowing web application.

Research Context:
{research[:3000]}

Mockup Context:
{mockups[:1500]}

Design Requirements:
1. Tech Stack: Node.js + Express + Prisma ORM + SQLite + React + Vite
2. Anonymous reporting with no tracking (IP only for rate limiting, hashed)
3. 5 report categories: Financial Misconduct, Fraud/Corruption, Harassment/Workplace Misconduct, Health & Safety Violation, Other
4. File uploads: Images (JPG, PNG) and PDFs, max 5MB, whitelist validation
5. Rate limiting: 5 submissions per hour per IP
6. JWT-based auth for Internal Audit and CEO roles only
7. Audit trail: Log who (auditor/CEO) viewed/escalated/resolved, but reporter remains anonymous
8. Status workflow: NEW -> IN_REVIEW -> ESCALATED or RESOLVED

Your output must include:

## 1. Database Schema (Prisma)
Complete prisma/schema.prisma file content with models:
- Report (with status enum)
- User (with role enum: AUDITOR, CEO)
- AuditLog (with action enum: VIEWED, ESCALATED, RESOLVED)

## 2. REST API Contract
Document all endpoints:
- POST /api/reports (anonymous submission)
- GET /api/reports (auditor view, with filters)
- PUT /api/reports/:id/status (auditor update)
- POST /api/reports/:id/escalate (auditor to CEO)
- GET /api/reports/escalated (CEO view)
- POST /api/auth/login (JWT login)
- GET /api/audit-log (auditor/CEO view)
- POST /api/upload (file upload)

## 3. Component Tree (React)
Frontend structure with routes and components

## 4. Security Model
- JWT strategy
- Password hashing (bcrypt)
- Rate limiting approach
- File upload security
- CORS configuration

## 5. Decision Log
Document major decisions with justifications:
- Why JWT over sessions?
- Why SQLite over PostgreSQL?
- Why Multer for uploads?
- Why separate CEO view?
"""
        
        print(f"[{self.name}] Invoking LLM for architecture design...")
        response = invoke_llm(SYSTEM_PROMPT, user_prompt, temperature=0.2)
        architecture_doc = response.content
        
        # Save architecture
        write_file("workspace/architecture.md", architecture_doc)
        print(f"[{self.name}] Architecture saved to workspace/architecture.md")
        
        # Extract and save decision log
        decision_log = self._extract_decisions(architecture_doc)
        write_file("workspace/decision_log.md", decision_log)
        print(f"[{self.name}] Decision log saved to workspace/decision_log.md")
        
        # Extract and save Prisma schema
        prisma_schema = self._extract_prisma_schema(architecture_doc)
        write_file("app/backend/prisma/schema.prisma", prisma_schema)
        print(f"[{self.name}] Prisma schema saved to app/backend/prisma/schema.prisma")
        
        return {
            **state,
            "architecture_doc": architecture_doc,
            "current_step": "architecture_complete"
        }
    
    def _extract_decisions(self, doc: str) -> str:
        """Extract decision log from architecture document."""
        lines = doc.split('\n')
        decision_lines = []
        in_decisions = False
        
        for line in lines:
            if '## 5. Decision Log' in line or '## Decision Log' in line:
                in_decisions = True
            elif in_decisions and line.startswith('## ') and 'Decision' not in line:
                break
            if in_decisions:
                decision_lines.append(line)
        
        header = "# Architecture Decision Log\n\nGenerated by ArchitectAgent\n\n"
        return header + '\n'.join(decision_lines) if decision_lines else header + "See architecture.md for decisions"
    
    def _extract_prisma_schema(self, doc: str) -> str:
        """Extract Prisma schema from architecture document."""
        lines = doc.split('\n')
        schema_lines = []
        in_schema = False
        
        for line in lines:
            if '```prisma' in line.lower() or ('datasource db' in line and not in_schema):
                in_schema = True
                if '```prisma' in line.lower():
                    continue
            elif in_schema and line.strip().startswith('```'):
                break
            if in_schema:
                schema_lines.append(line)
        
        if not schema_lines:
            # Fallback: generate a standard schema
            return """generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id        Int      @id @default(autoincrement())
  username  String   @unique
  password  String
  role      Role     @default(AUDITOR)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  auditLogs AuditLog[]
}

model Report {
  id          Int      @id @default(autoincrement())
  category    Category
  message     String
  filePath    String?
  status      Status   @default(NEW)
  ipHash      String?
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  auditLogs   AuditLog[]
}

model AuditLog {
  id        Int      @id @default(autoincrement())
  action    Action
  userId    Int
  reportId  Int
  createdAt DateTime @default(now())
  user      User     @relation(fields: [userId], references: [id])
  report    Report   @relation(fields: [reportId], references: [id])
}

enum Role {
  AUDITOR
  CEO
}

enum Category {
  FINANCIAL_MISCONDUCT
  FRAUD_CORRUPTION
  HARASSMENT_WORKPLACE
  HEALTH_SAFETY
  OTHER
}

enum Status {
  NEW
  IN_REVIEW
  ESCALATED
  RESOLVED
}

enum Action {
  VIEWED
  ESCALATED
  RESOLVED
  STATUS_CHANGED
}
"""
        
        return '\n'.join(schema_lines)
